version: '3.7'

services:
    postgres-personal:
        container_name: '${PG_NAME:-postgres-personal}'
        image: postgres
        volumes:
            - ../var/pgdata:/var/lib/postgresql/data
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdata
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=fastapi
        networks:
            - fastapinet
        ports:
            - "5433:5432"

networks:
  fastapinet:
    external:
      name: personalnet

volumes:
    postgres:
